name: Daily Court List Fetch

on:
  schedule:
    - cron: '0 23 * * 1-5'  # 9am AEST weekdays
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run court scraper
      run: |
        python court_scraper.py

    - name: Commit & push if there are changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "court-scraper-bot"
        git config user.email "court-scraper@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add -A
        git diff-index --quiet HEAD || git commit -m "Daily update $(date '+%Y-%m-%d')"
        git push origin HEAD:main
